# https://kubernetes.io/docs/user-guide/deployments/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: http-echo
          image: "foo/http-echo:1.0.0"
          ports:
            - containerPort: 8080
